CREATE DATABASE QLBH_DIENMAYDO1
GO

USE QLBH_DIENMAYDO1
GO

CREATE TABLE KHUYENMAI
(
MAKM VARCHAR(10) NOT NULL,
TENCT NVARCHAR(100) NOT NULL,
HINHTHUC NVARCHAR(100) NOT NULL,
BATDAU DATE NOT NULL,
KETTHUC DATE NOT NULL,
GIAMGIA MONEY NOT NULL,
TRANGTHAI BIT NOT NULL,
MOTA NVARCHAR(200),
PRIMARY KEY (MAKM)
)
GO
	
CREATE TABLE DANHMUC
(
MADANHMUC VARCHAR(10) NOT NULL,
TENDM NVARCHAR(100) NOT NULL,
TRANGTHAI BIT NOT NULL,
GHICHU NVARCHAR(200),
PRIMARY KEY (MADANHMUC) ,
)
GO


CREATE TABLE NHANVIEN
(
MANV VARCHAR(10) NOT NULL,
MATKHAU VARCHAR(100) NOT NULL,
TENNV NVARCHAR(100) NOT NULL,
DIACHI NVARCHAR(100) NOT NULL,
DIENTHOAI VARCHAR(12) NOT NULL,
GIOITINH BIT NOT NULL,
NGAYSINH DATE NOT NULL,
VAITRO BIT NOT NULL,
TRANGTHAI BIT NOT NULL,
PRIMARY KEY (MANV)
)
GO

CREATE TABLE XUATXU
(
MAXX INT IDENTITY(1,1) NOT NULL,
NHASX NVARCHAR(100) NOT NULL,
NUOCSX NVARCHAR(100) NOT NULL,
PRIMARY KEY(MAXX)
)
GO

CREATE TABLE SANPHAM
(
MASP VARCHAR(10) NOT NULL,
MADANHMUC VARCHAR(10) NOT NULL,
MAXX INT NOT NULL,
TENSP NVARCHAR(50) NOT NULL,
TRANGTHAISP BIT NOT NULL,
PRIMARY KEY (MASP),
FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC (MADANHMUC),
FOREIGN KEY (MAXX) REFERENCES XUATXU (MAXX),
)
GO


CREATE TABLE KHACHHANG
(
MAKH VARCHAR(10) NOT NULL,
TENKH NVARCHAR(100) NOT NULL,
GIOITINH BIT NOT NULL,
DIENTHOAI VARCHAR(12) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DIACHI NVARCHAR(100) NOT NULL,
TRANGTHAI BIT NOT NULL,
PRIMARY KEY (MAKH)
)
GO

CREATE TABLE TRANGTHAITHANHTOAN
(
MATTTT VARCHAR(10) NOT NULL,
TENTTTT NVARCHAR(100) NOT NULL,
PRIMARY KEY(MATTTT)
)
GO

CREATE TABLE HINHTHUCTHANHTOAN
(
MAHTTT VARCHAR(10) NOT NULL,
TENHTTT NVARCHAR(100) NOT NULL,
PRIMARY KEY(MAHTTT)
)
GO

CREATE TABLE HINHTHUCGIAOHANG
(
MAHTGH VARCHAR(10) NOT NULL,
TENHTGH NVARCHAR(100) NOT NULL,
PRIMARY KEY(MAHTGH)
)
GO

CREATE TABLE HOADON
(
MAHD INT IDENTITY(1,1) NOT NULL,
MANV VARCHAR(10) NOT NULL,
MAKH VARCHAR(10) NOT NULL,
MATTTT VARCHAR(10) NOT NULL,
MAHTTT VARCHAR(10) NOT NULL,
MAHTGH VARCHAR(10) NOT NULL,
NGAYLAP DATE DEFAULT GETDATE() NOT NULL,
TIENTHUATRAKHACH MONEY NOT NULL,
TONGTIEN MONEY NOT NULL,
GHICHU NVARCHAR(200),
PRIMARY KEY (MAHD),
FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
FOREIGN KEY (MATTTT) REFERENCES TRANGTHAITHANHTOAN (MATTTT),
FOREIGN KEY (MAHTTT) REFERENCES HINHTHUCTHANHTOAN (MAHTTT),
FOREIGN KEY (MAHTGH) REFERENCES HINHTHUCGIAOHANG (MAHTGH),
)
GO

CREATE TABLE MAUSAC
(
MAMAUSAC VARCHAR(10) NOT NULL,
TENMAUSAC NVARCHAR(50) NOT NULL,
PRIMARY KEY(MAMAUSAC)
)
GO

CREATE TABLE DONVITINH
(
MADV VARCHAR(10) NOT NULL,
TENDV NVARCHAR(50) NOT NULL,
PRIMARY KEY(MADV)
)
GO

CREATE TABLE KICHTHUOC
(
MAKICHTHUOC VARCHAR(10) NOT NULL,
MADV VARCHAR(10) NOT NULL,
CHIEUDAI FLOAT NOT NULL,
CHIEURONG FLOAT NOT NULL,
CHIEUCAO FLOAT NOT NULL,
PRIMARY KEY(MAKICHTHUOC),
FOREIGN KEY (MADV) REFERENCES DONVITINH(MADV)
)
GO

CREATE TABLE KHOILUONG
(
MAKL VARCHAR(10) NOT NULL,
MADV VARCHAR(10) NOT NULL,
KHOILUONG FLOAT NOT NULL,
PRIMARY KEY(MAKL),
FOREIGN KEY (MADV) REFERENCES DONVITINH(MADV)
)
GO

CREATE TABLE THETICH
(
MATHETICH VARCHAR(10) NOT NULL,
THETICH FLOAT NOT NULL,
PRIMARY KEY(MATHETICH)
)
GO

CREATE TABLE CHATLIEU
(
MACHATLIEU VARCHAR(10) NOT NULL,
CHATLIEU NVARCHAR(100) NOT NULL,
PRIMARY KEY(MACHATLIEU)
)
GO

CREATE TABLE _IMAGE
(
MAIMAGE VARCHAR(10) NOT NULL,
TENHINH NVARCHAR(100) NOT NULL,
PRIMARY KEY(MAIMAGE)
)
GO

CREATE TABLE SANPHAMCHITIET
(
MASPCT VARCHAR(10) NOT NULL,
MAIMAGE VARCHAR(10) NOT NULL,
MASP VARCHAR(10) NOT NULL,
MAMAUSAC VARCHAR(10) NOT NULL,
MAKICHTHUOC VARCHAR(10) NOT NULL,
MACHATLIEU VARCHAR(10) NOT NULL,
MATHETICH VARCHAR(10) NOT NULL,
MAKL VARCHAR(10) NOT NULL,
TENSPCT NVARCHAR(50) NOT NULL,
SOLUONG INT NOT NULL,
NHOMPHOBIEN BIT NOT NULL,
GIANHAP MONEY NOT NULL,
GIABAN MONEY NOT NULL,
TRANGTHAI BIT NOT NULL,
MOTA NVARCHAR(200),
PRIMARY KEY(MASPCT),
FOREIGN KEY (MAIMAGE) REFERENCES _IMAGE(MAIMAGE),
FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP) ON DELETE CASCADE,
FOREIGN KEY (MAMAUSAC) REFERENCES MAUSAC(MAMAUSAC),
FOREIGN KEY (MAKICHTHUOC) REFERENCES KICHTHUOC(MAKICHTHUOC),
FOREIGN KEY (MACHATLIEU) REFERENCES CHATLIEU(MACHATLIEU),
FOREIGN KEY (MATHETICH) REFERENCES THETICH(MATHETICH),
FOREIGN KEY (MAKL) REFERENCES KHOILUONG(MAKL)
)
GO

CREATE TABLE HOADONCHITIET
(
MAHDCT INT IDENTITY(1,1) NOT NULL,
MASPCT VARCHAR(10) NOT NULL,
MAHD INT NOT NULL,
SOLUONG INT NOT NULL,
DONGIA MONEY NOT NULL,
PRIMARY KEY (MAHDCT),
FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
FOREIGN KEY (MASPCT) REFERENCES SANPHAMCHITIET (MASPCT),
)
GO

CREATE TABLE SANPHAMCHITIET_KHUYENMAI
(
MASPCTKM INT IDENTITY(1,1) NOT NULL,
MAKM VARCHAR(10) NOT NULL,
MASPCT VARCHAR(10) NOT NULL,
PRIMARY KEY(MASPCTKM),
FOREIGN KEY (MAKM) REFERENCES KHUYENMAI (MAKM),
FOREIGN KEY (MASPCT) REFERENCES SANPHAMCHITIET (MASPCT)
)
GO

--BẢNG THỐNG KÊ
IF OBJECT_ID('SP_TABLETKTT') IS NOT NULL
	DROP PROC SP_TABLETKTT
GO
CREATE PROC SP_TABLETKTT(@YEAR INT)
AS
	BEGIN
		SELECT
			TENSP AS TENSANPHAM,
			HOADONCHITIET.SOLUONG AS SOLUONGSP,
			MAX(GIABAN) AS GIABANCAONHAT,
			MIN(GIABAN) AS GIABANTHAPNHAT,
			TONGTIEN AS DOANHTHU
		FROM HOADON JOIN HOADONCHITIET ON HOADONCHITIET.MAHD = HOADON.MAHD
					JOIN SANPHAMCHITIET ON SANPHAMCHITIET.MASPCT = HOADONCHITIET.MASPCT
					JOIN SANPHAM ON SANPHAM.MASP = SANPHAMCHITIET.MASP
					JOIN DANHMUC ON DANHMUC.MADANHMUC = SANPHAM.MADANHMUC
		WHERE YEAR(NGAYLAP) = @YEAR
		GROUP BY TENSP, HOADONCHITIET.SOLUONG, TONGTIEN
	END
	EXEC SP_TABLETKTT 2021

--THỐNG KÊ HÀNG HỦY
IF OBJECT_ID('SP_HANGHUY') IS NOT NULL
	DROP PROC SP_HANGHUY
GO
CREATE PROC SP_HANGHUY(@YEAR INT)
AS
	BEGIN
		SELECT
			MAHD AS MAHOADON,
			TONGTIEN AS TONGTIEN,
			TENHTTT AS HINHTHUCTHANHTOAN,
			NGAYLAP AS NGAYLAPHOADON,
			TENKH AS TENKHACHHANG,
			GHICHU AS GHICHU
		FROM HOADON JOIN TRANGTHAITHANHTOAN ON TRANGTHAITHANHTOAN.MATTTT = HOADON.MATTTT
					JOIN HINHTHUCTHANHTOAN ON HINHTHUCTHANHTOAN.MAHTTT = HOADON.MAHTTT
					JOIN KHACHHANG ON KHACHHANG.MAKH = HOADON.MAKH
		WHERE YEAR(NGAYLAP) = @YEAR AND TRANGTHAITHANHTOAN.MATTTT = 'TT003'
		GROUP BY MAHD,TONGTIEN,TENHTTT,NGAYLAP,TENKH,GHICHU
	END
	EXEC SP_HANGHUY 2019