CREATE DATABASE QLBHDIENMAY_TSOFTWEAR
GO
USE QLBHDIENMAY_TSOFTWEAR
GO
CREATE TABLE NGUYENVATLIEU(
MaNVL VARCHAR(10),
TenNVL NVARCHAR(50),
PRIMARY KEY(MaNVL)
)
GO
CREATE TABLE NHOMHANHOA(
MaNHH VARCHAR(10),
TenNHH NVARCHAR(50),
GHICHU NVARCHAR(200),
PRIMARY KEY (MaNHH)
)
GO
CREATE TABLE NHANVIEN(
MaNV VARCHAR(10),
TenNV NVARCHAR(50),
DIACHI NVARCHAR(50),
DIENTHOAI VARCHAR(12),
GIOITINH BIT,
NGAYSINH DATE,
PRIMARY KEY (MANV) 
)
GO
CREATE TABLE SANPHAM(
MASP VARCHAR(10),
MANHH VARCHAR(10),
MANVL VARCHAR(10),
TENSP NVARCHAR(50),
NHOMPHOBIEN BIT,
NHASX NVARCHAR(50),
NUOCSX NVARCHAR(50),
SOLUONG INT,
GIANHAP MONEY,
GIABAN MONEY,
MOTA NVARCHAR(100),
PRIMARY KEY (MASP),
FOREIGN KEY (MANHH) REFERENCES NHOMHANHOA (MANHH),
FOREIGN KEY (MANVL) REFERENCES NGUYENVATLIEU (MANVL)
)
GO
CREATE TABLE TAIKHOAN(
MANV VARCHAR(10),
MATKHAU VARCHAR(50),
VAITRO BIT,
PRIMARY KEY(MANV),
FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
)
GO
CREATE TABLE KHACHHANG(
MAKH VARCHAR(10),
TENKH NVARCHAR(50),
DIENTHOAI VARCHAR(12),
EMAIL VARCHAR(50),
DIACHI NVARCHAR(50),
PRIMARY KEY (MAKH)
)
GO
CREATE TABLE HOADON(
MAHD VARCHAR(10),
MANV VARCHAR(10),
MAKH VARCHAR(10),
NGAYLAP DATE,
TRANGTHAITT NVARCHAR(30),
HINHTHUCTT NVARCHAR(30),
TONGTIEN MONEY,
GHICHU NVARCHAR(100),
PRIMARY KEY (MAHD),
FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)
GO
CREATE TABLE HOADONDOITRA(
MAHDDT VARCHAR(10),
MAHD VARCHAR(10),
MANV VARCHAR(10),
DONGIA MONEY,
NGAYLAP DATE,
MOTA NVARCHAR(100),
PRIMARY KEY (MAHDDT),
FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
) 
GO
CREATE TABLE HOADONCHITIET(
MAHD VARCHAR(10),
MASP VARCHAR(10),
SOLUONG INT,
DONGIA MONEY,
GIAMGIA MONEY,
THANHTIEN MONEY,
PRIMARY KEY (MAHD , MASP ) ,
FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD),
FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
)
GO
CREATE TABLE VOUCHER (
MAVOUCHER VARCHAR(10),
MANHH VARCHAR(10),
NGAYTAO DATE,
NGAYHETHAN DATE,
SOLUONG INT,
MENHGIA MONEY,
TRANGTHAI BIT,
GHICHU NVARCHAR(100),
PRIMARY KEY (MAVOUCHER),
FOREIGN KEY (MANHH) REFERENCES NHOMHANHOA (MANHH)
)
GO
CREATE TABLE KHUYENMAI(
MAKM VARCHAR(10),
MANHH VARCHAR(10),
TENCT NVARCHAR(50),
HINHTHUC NVARCHAR(100),
BATDAU DATE,
KETTHUC DATE,
GIAMGIA FLOAT,
MOTA NVARCHAR(100),
PRIMARY KEY (MAKM),
FOREIGN KEY(MANHH) REFERENCES NHOMHANHOA (MANHH)
)
GO

-- test Sua guit




