/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dienmaydo.gui;

import com.dienmaydo.entity.DanhMuc;
import com.dienmaydo.entity.HinhThucGiaoHang;
import com.dienmaydo.entity.HinhThucThanhToan;
import com.dienmaydo.entity.HoaDon;
import com.dienmaydo.entity.HoaDonChiTiet;
import com.dienmaydo.entity.SanPhamChiTiet;
import com.dienmaydo.service.DanhMucService;
import com.dienmaydo.service.HinhThucGiaoHangService;
import com.dienmaydo.service.HinhThucThanhToanService;
import com.dienmaydo.service.HoaDonChiTietService;
import com.dienmaydo.service.HoaDonService;
import com.dienmaydo.service.SanPhamChiTietService;
import com.dienmaydo.utils.Auth;
import com.dienmaydo.utils.Msgbox;
import com.dienmaydo.utils.XDate;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DO TAT HOA
 */
public class F_BanHang extends javax.swing.JInternalFrame implements Runnable, ThreadFactory {

    DefaultTableModel model1;
    DefaultTableModel model2;
    DefaultTableModel model3;
    SanPhamChiTietService spService = new SanPhamChiTietService();
    HoaDonService hdService = new HoaDonService();
    DanhMucService dmService = new DanhMucService();
    HinhThucThanhToanService htttService = new HinhThucThanhToanService();
    HinhThucGiaoHangService htghService = new HinhThucGiaoHangService();
    HoaDonChiTietService hdctService = new HoaDonChiTietService();
    int row1 = -1;
    int row2 = -1;
    int row3 = -1;

    private WebcamPanel panel = null;
    public static Webcam webcam = null;

    private static final long serialVersionUID = 6441489157408381878L;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    /**
     * Creates new form F_BanHang
     */
    public F_BanHang() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setResizable(false);

        model1 = (DefaultTableModel) tblChonSanPham.getModel();
        model2 = (DefaultTableModel) tblSanPhamChon.getModel();
        model3 = (DefaultTableModel) tblHoaDonCho.getModel();
        fillCBOHinhThucGiaoHang();
        fillCBOHinhThucThanhToan();
        fillCboDanhMuc();
        showHoaDonCho();
        initWebcam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPhamChon = new javax.swing.JTable();
        btnXoaSP = new javax.swing.JButton();
        btnXoaTatCa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChonSanPham = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnThemSanPham = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtghiChu = new javax.swing.JTextArea();
        lblGiamGia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboHinhThucTT = new javax.swing.JComboBox<>();
        txtMaHoaDon = new javax.swing.JTextField();
        btnHuyHoaDon = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblKhacCanTra = new javax.swing.JLabel();
        txtTienTraKhach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboHinhThucGiaoHang = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDonCho = new javax.swing.JTable();
        webCamPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1146, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1146, 768));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các sản phẩm đã chọn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblSanPhamChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamChon.setRowHeight(25);
        jScrollPane1.setViewportView(tblSanPhamChon);

        btnXoaSP.setBackground(new java.awt.Color(255, 204, 0));
        btnXoaSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaSP.setForeground(new java.awt.Color(51, 51, 51));
        btnXoaSP.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\delete_26px.png")); // NOI18N
        btnXoaSP.setText("Xóa sản phẩm");
        btnXoaSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnXoaSP.setPreferredSize(new java.awt.Dimension(60, 30));
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        btnXoaTatCa.setBackground(new java.awt.Color(255, 204, 0));
        btnXoaTatCa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaTatCa.setForeground(new java.awt.Color(51, 51, 51));
        btnXoaTatCa.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\delete_26px.png")); // NOI18N
        btnXoaTatCa.setText("Xóa tất cả");
        btnXoaTatCa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnXoaTatCa.setPreferredSize(new java.awt.Dimension(60, 30));
        btnXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTatCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnXoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblChonSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Màu sắc", "Chất liệu", "Kích thước", "Thể tích", "Số lượng tồn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChonSanPham.setRowHeight(25);
        jScrollPane2.setViewportView(tblChonSanPham);

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tìm kiếm sản phẩm:");

        btnThemSanPham.setBackground(new java.awt.Color(255, 204, 0));
        btnThemSanPham.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemSanPham.setForeground(new java.awt.Color(51, 51, 51));
        btnThemSanPham.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\add_24px.png")); // NOI18N
        btnThemSanPham.setText("Thêm sản phẩm");
        btnThemSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnThemSanPham.setPreferredSize(new java.awt.Dimension(60, 30));
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Danh mục:");

        cboDanhMuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDanhMucItemStateChanged(evt);
            }
        });
        cboDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDanhMucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(161, 161, 161))
                            .addComponent(cboDanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnThemSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnLuu.setBackground(new java.awt.Color(255, 204, 0));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\save_16px.png")); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Giảm giá:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tổng tiền:");

        txtghiChu.setColumns(20);
        txtghiChu.setRows(5);
        jScrollPane3.setViewportView(txtghiChu);

        lblGiamGia.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã hóa đơn:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Hình thức thanh toán:");

        txtMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHoaDonActionPerformed(evt);
            }
        });

        btnHuyHoaDon.setBackground(new java.awt.Color(255, 204, 0));
        btnHuyHoaDon.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnHuyHoaDon.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\update_16px.png")); // NOI18N
        btnHuyHoaDon.setText("Hủy hóa đơn");
        btnHuyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHoaDonActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 204, 0));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\refresh_16px.png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lblKhacCanTra.setText("0");

        txtTienTraKhach.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tiền thừa trả khách:");

        lblTongTien.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Ghi chú:");

        btnThanhToan.setBackground(new java.awt.Color(255, 204, 0));
        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(51, 51, 51));
        btnThanhToan.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\create_26px.png")); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Khách cần trả:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Hình thức giao hàng:");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnShow.setBackground(new java.awt.Color(255, 204, 0));
        btnShow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnShow.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\show_password_16px.png")); // NOI18N
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnChon.setBackground(new java.awt.Color(255, 204, 0));
        btnChon.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnChon.setIcon(new javax.swing.ImageIcon("D:\\FPT\\PRO1041\\SQL\\DuAn1\\Dien_May_Do\\src\\com\\dienmaydo\\icon\\save_16px.png")); // NOI18N
        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mã khách hàng:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tên khách hàng:");

        lblTenKH.setText(" ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShow)
                    .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChon, btnShow});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnChon)
                    .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShow)
                    .addComponent(jLabel7)
                    .addComponent(lblTenKH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHuyHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTienTraKhach)
                            .addComponent(lblKhacCanTra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGiamGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboHinhThucGiaoHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHinhThucTT, 0, 185, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuyHoaDon, btnLamMoi});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTongTien))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblGiamGia))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblKhacCanTra))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTienTraKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHinhThucTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboHinhThucGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnHuyHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chờ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblHoaDonCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày tạo", "Nhân viên tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonCho.setRowHeight(25);
        tblHoaDonCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDonCho);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        webCamPanel.setBackground(new java.awt.Color(255, 255, 255));
        webCamPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quét mã sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        webCamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        webCamPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webCamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webCamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        // TODO add your handling code here:
        themSanPham();
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void btnXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaActionPerformed
        // TODO add your handling code here:
        xoaTatCa();
    }//GEN-LAST:event_btnXoaTatCaActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        xoaSanPham();
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void cboDanhMucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDanhMucItemStateChanged
        // TODO add your handling code here:
        showProductsDM();
    }//GEN-LAST:event_cboDanhMucItemStateChanged

    private void cboDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDanhMucActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        thanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHoaDonActionPerformed
        // TODO add your handling code here:
        huyHoaDon();
    }//GEN-LAST:event_btnHuyHoaDonActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        luuHoaDon();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblHoaDonChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChoMouseClicked
        // TODO add your handling code here:
        clickHoaDonCho();
    }//GEN-LAST:event_tblHoaDonChoMouseClicked

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        KhachHangJframe kh = new KhachHangJframe();
        kh.setVisible(true);
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        showTTKH();
    }//GEN-LAST:event_btnShowActionPerformed

    private void txtMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnHuyHoaDon;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JButton btnXoaTatCa;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboHinhThucGiaoHang;
    private javax.swing.JComboBox<String> cboHinhThucTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblKhacCanTra;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblChonSanPham;
    private javax.swing.JTable tblHoaDonCho;
    private javax.swing.JTable tblSanPhamChon;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtTienTraKhach;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextArea txtghiChu;
    private javax.swing.JPanel webCamPanel;
    // End of variables declaration//GEN-END:variables

    public void themSanPham() {
        row1 = tblChonSanPham.getSelectedRow();
        row3 = tblHoaDonCho.getSelectedRow();
        try {
            if (row3 < 0) {
                Msgbox.alert(this, "Vui lòng chọn hóa đơn chờ\nNếu chưa có vui lòng tạo!");
            } else if (row1 < 0) {
                Msgbox.alert(this, "Vui lòng chọn sản phẩm trên table!");
            } else {
                String soluong = Msgbox.prompt(this, "Mời bạn nhập số lượng sản phẩm:");
                if (Integer.parseInt(soluong) > Integer.parseInt(tblChonSanPham.getValueAt(row1, 7) + "")) {
                    Msgbox.alert(this, "Số lượng sản phẩm bạn vừa nhập vượt quá số lượng trong kho!");
                    return;
                } else if (Integer.parseInt(soluong) < 0) {
                    Msgbox.alert(this, "Số lượng sản phẩm không được nhỏ hơn 0!");
                    return;
                } else {
                    for (int i = 0; i < tblSanPhamChon.getRowCount(); i++) {
                        if (tblSanPhamChon.getValueAt(i, 0).toString().equals(tblChonSanPham.getValueAt(row1, 0))) {
                            int soLuongGoc = Integer.parseInt(tblSanPhamChon.getValueAt(i, 3) + "");
                            tblSanPhamChon.setValueAt(soLuongGoc + Integer.parseInt(soluong), i, 3);
                            donHang();
                            capNhatHoaDon();
                            //Cập nhật số lượng sản phẩm tồn (begin)
                            SanPhamChiTiet s = spService.selectByID(tblChonSanPham.getValueAt(row1, 0) + "");
                            int soLuongMoi = (s.getSoLuong() - Integer.parseInt(soluong));

                            SanPhamChiTiet sp = new SanPhamChiTiet();
                            sp.setSoLuong(soLuongMoi);
                            sp.setMaSPCT(tblChonSanPham.getValueAt(row1, 0) + "");
                            spService.updateBanHang(sp);
                            // cập nhật số lượng sản phầm tồn (end)
                            fillTable();
                            return;
                        }
                    }
                    Vector v = new Vector();
                    v.add(tblChonSanPham.getValueAt(row1, 0));
                    v.add(tblChonSanPham.getValueAt(row1, 1));
                    v.add(tblChonSanPham.getValueAt(row1, 2));
                    v.add(soluong);
                    model2.addRow(v);
                    donHang();
                    capNhatHoaDon();
                    //Cập nhật số lượng sản phẩm tồn (begin)
                    SanPhamChiTiet s = spService.selectByID(tblChonSanPham.getValueAt(row1, 0) + "");
                    int soLuongMoi = (s.getSoLuong() - Integer.parseInt(soluong));

                    SanPhamChiTiet sp = new SanPhamChiTiet();
                    sp.setSoLuong(soLuongMoi);
                    sp.setMaSPCT(tblChonSanPham.getValueAt(row1, 0) + "");
                    spService.updateBanHang(sp);
                    // cập nhật số lượng sản phầm tồn (end)
                    fillTable();
                }
            }
        } catch (NumberFormatException e) {
            Msgbox.alert(this, "Số lượng sản phẩm phải là số nguyên");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void capNhatHoaDon() {
        HoaDon hd = getForm();
        hdService.update(hd);
        hdctService.delete(txtMaHoaDon.getText());
        for (int i = 0; i < tblSanPhamChon.getRowCount(); i++) {
            HoaDonChiTiet hdct = new HoaDonChiTiet();
            hdct.setMaSPCT(tblSanPhamChon.getValueAt(i, 0) + "");
            hdct.setMaHD(txtMaHoaDon.getText());
            hdct.setSoLuong(Integer.parseInt(tblSanPhamChon.getValueAt(i, 3) + ""));
            hdct.setDonGia(Float.parseFloat(tblSanPhamChon.getValueAt(i, 2) + ""));
            hdctService.insert(hdct);
        }
    }

    public void huyHoaDon() {
        HinhThucGiaoHang htgh = (HinhThucGiaoHang) cboHinhThucGiaoHang.getSelectedItem();
        HinhThucThanhToan httt = (HinhThucThanhToan) cboHinhThucTT.getSelectedItem();

        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHoaDon.getText());
        hd.setMaHTTT(httt.getMaHTTT());
        hd.setMaTTTT("TT003");
        hd.setMaHTGH(htgh.getMaHTGH());
        hd.setTienThuaTraKhach(Float.parseFloat(txtTienTraKhach.getText()));
        hd.setTongTien(Float.parseFloat(lblTongTien.getText()));
        hd.setGhiChu(txtghiChu.getText());
        try {
            if (txtMaHoaDon.getText().trim().equals("")) {
                Msgbox.alert(this, "Vui lòng chọn hóa đơn để hủy");
            } else {
                if (Msgbox.confirm(this, "Bạn chắc chắn muốn hủy hóa đơn này ?")) {
                    hdService.update(hd);
                    capNhatSoluongXoaAll();
                    donHang();
                    showHoaDonCho();
                    showProductsDM();
                    lamMoi();
                    Msgbox.alert(this, "Hóa đơn đã được hủy!");
                }
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Hủy hóa đơn thất bại");
            e.printStackTrace();
        }
    }

    public void xoaSanPham() {
        row2 = tblSanPhamChon.getSelectedRow();
        try {
            if (row2 < 0) {
                Msgbox.alert(this, "Vui lòng chọn sản phẩm để xóa!");
                return;
            } else {
                if (Msgbox.confirm(this, "Bạn chắc chắn muốn xóa sản phẩm này khỏi danh sách đã chọn?")) {
                    capNhatSoLuongXoaSP();
                    model2.removeRow(row2);
                    donHang();
                    capNhatHoaDon();
                    fillTable();
                    Msgbox.alert(this, "Xóa sản phẩm thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            Msgbox.alert(this, "Xóa sản phẩm thất bại");
        }
    }

    public void xoaTatCa() {
        try {
            if (Msgbox.confirm(this, "Bạn chắc chắn muốn xóa hết tất cả sản phẩm này khỏi danh sách đã chọn ?")) {
                capNhatSoluongXoaAll();
                model2.setRowCount(0);
                donHang();
                capNhatHoaDon();
                fillTable();
                Msgbox.alert(this, "Xóa tất cả sản phẩm thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            Msgbox.alert(this, "Xóa tất cả sản phẩm thất bại");
        }
    }

    public void timKiem() {
        if (txtTimKiem.getText().trim().equals("")) {
            fillTable();
            cboDanhMuc.setSelectedIndex(0);
        } else {
            model1.setRowCount(0);
            List<SanPhamChiTiet> list = spService.selectByTimKiem(txtTimKiem.getText().trim());
            for (SanPhamChiTiet x : list) {
                model1.addRow(new Object[]{
                    x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getGiaBan(), x.getTenMauSac(), x.getTenChatLieu(), x.getChieuDai() + "cm X " + x.getChieuRong() + "cm X " + x.getChieuCao() + "cm",
                    x.getTheTich(), x.getSoLuong()
                });
            }
            cboDanhMuc.setSelectedIndex(0);
        }
    }

    public void donHang() {
        float tongTien = 0;
        int soDong = tblSanPhamChon.getRowCount();
        if (soDong == 0) {
            lblTongTien.setText("0");
            lblGiamGia.setText("0");
            lblKhacCanTra.setText("0");
            txtTienTraKhach.setText("0");
        } else {
            for (int i = 0; i < tblSanPhamChon.getRowCount(); i++) {
                float donGia = Float.parseFloat(tblSanPhamChon.getValueAt(i, 2) + "");
                int soLuong = Integer.parseInt(tblSanPhamChon.getValueAt(i, 3) + "");
                tongTien += (float) (soLuong * donGia);

                lblTongTien.setText(tongTien + "");
                lblGiamGia.setText("0");
                lblKhacCanTra.setText(tongTien + "");
            }

        }
    }

    public void thanhToan() {
        HinhThucGiaoHang htgh = (HinhThucGiaoHang) cboHinhThucGiaoHang.getSelectedItem();
        HinhThucThanhToan httt = (HinhThucThanhToan) cboHinhThucTT.getSelectedItem();

        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHoaDon.getText());
        hd.setMaHTTT(httt.getMaHTTT());
        hd.setMaTTTT("TT002");
        hd.setMaHTGH(htgh.getMaHTGH());
        hd.setTienThuaTraKhach(Float.parseFloat(txtTienTraKhach.getText()));
        hd.setTongTien(Float.parseFloat(lblTongTien.getText()));
        hd.setGhiChu(txtghiChu.getText());
        try {
            if (txtMaHoaDon.getText().equals("")) {
                Msgbox.alert(this, "Vui lòng chọn hóa đơn trước khi nhấn thanh toán");
                return;
            } else if (tblSanPhamChon.getRowCount() == 0) {
                Msgbox.alert(this, "Vui lòng chọn sản phẩm trước khi nhấn thanh toán");
                return;
            } else {
                if (Msgbox.confirm(this, "Bạn chắc chắn muốn thanh toán hóa đơn này chứ?")) {
                    hdService.update(hd);
                    showHoaDonCho();
                    showProductsDM();
                    xuatHoaDon();
                    lamMoi();
                    Msgbox.alert(this, "Thanh toán thành công!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            Msgbox.alert(this, "Thanh toán thất bại");
        }
    }

    public void capNhatSoluongXoaAll() {
        for (int i = 0; i < tblSanPhamChon.getRowCount(); i++) {
            SanPhamChiTiet s = spService.selectByID(tblSanPhamChon.getValueAt(i, 0) + "");
            int soLuongMoi = (s.getSoLuong() + Integer.parseInt(tblSanPhamChon.getValueAt(i, 3) + ""));

            SanPhamChiTiet sp = new SanPhamChiTiet();
            sp.setSoLuong(soLuongMoi);
            sp.setMaSPCT(tblSanPhamChon.getValueAt(i, 0) + "");
            spService.updateBanHang(sp);
        }
    }

    public void capNhatSoLuongXoaSP() {
        row2 = tblSanPhamChon.getSelectedRow();
        SanPhamChiTiet s = spService.selectByID(tblSanPhamChon.getValueAt(row2, 0) + "");
        int soLuongMoi = (s.getSoLuong() + Integer.parseInt(tblSanPhamChon.getValueAt(row2, 3) + ""));

        SanPhamChiTiet sp = new SanPhamChiTiet();
        sp.setSoLuong(soLuongMoi);
        sp.setMaSPCT(tblSanPhamChon.getValueAt(row2, 0) + "");
        spService.updateBanHang(sp);
    }

    HoaDon getForm() {
        HinhThucGiaoHang htgh = (HinhThucGiaoHang) cboHinhThucGiaoHang.getSelectedItem();
        HinhThucThanhToan httt = (HinhThucThanhToan) cboHinhThucTT.getSelectedItem();

        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHoaDon.getText());
        hd.setMaNV(Auth.user.getMaNV());
        hd.setMaKH(lblMaKH.getText());
        hd.setMaHTTT(httt.getMaHTTT());
        hd.setMaTTTT("TT001");
        hd.setMaHTGH(htgh.getMaHTGH());
        hd.setTienThuaTraKhach(Float.parseFloat(txtTienTraKhach.getText()));
        hd.setTongTien(Float.parseFloat(lblTongTien.getText()));
        hd.setGhiChu(txtghiChu.getText());
        return hd;
    }

    public void lamMoi() {
        model2.setRowCount(0);
        txtMaHoaDon.setText("");
        lblMaKH.setText("");
        lblTenKH.setText("");
        lblTongTien.setText("0");
        lblGiamGia.setText("0");
        lblKhacCanTra.setText("0");
        txtTienTraKhach.setText("0");
        cboHinhThucTT.setSelectedIndex(0);
        cboHinhThucGiaoHang.setSelectedIndex(0);
        txtghiChu.setText("");
        row2 = -1;
        txtMaHoaDon.setEditable(true);
    }

    public void fillCboDanhMuc() {
        cboDanhMuc.addItem("   ");
        List<DanhMuc> list = dmService.selectAll();
        for (int i = 0; i < list.size(); i++) {
            cboDanhMuc.addItem(list.get(i).getTenDanhMuc());
        }
    }

    public void showProductsDM() {
        if (cboDanhMuc.getSelectedIndex() == 0) {
            fillTable();
        }
        if (cboDanhMuc.getSelectedIndex() > 0) {
            model1.setRowCount(0);
            List<SanPhamChiTiet> list = spService.selectByDM(cboDanhMuc.getSelectedItem() + "");
            for (SanPhamChiTiet x : list) {
                model1.addRow(new Object[]{
                    x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getGiaBan(), x.getTenMauSac(), x.getTenChatLieu(), x.getChieuDai() + "cm X " + x.getChieuRong() + "cm X " + x.getChieuCao() + "cm",
                    x.getTheTich(), x.getSoLuong()
                });
            }
            txtTimKiem.setText("");
        }
    }

    public void luuHoaDon() {
        try {
            if (txtMaHoaDon.getText().trim().equals("")) {
                Msgbox.alert(this, "Vui lòng nhập mã hóa đơn trước khi lưu");
                return;
            } else if (lblMaKH.getText().trim().equals("")) {
                Msgbox.alert(this, "Vui lòng chọn khách hàng trước khi nhấn lưu hóa đơn");
                return;
            } else if (checkTrungMaHD(txtMaHoaDon.getText())) {
                Msgbox.alert(this, "Mã hóa đơn đã tồn tại");
                return;
            } else {
                hdService.insert(getForm());
                showHoaDonCho();
                Msgbox.alert(this, "Lưu hóa đơn thành công");

                txtMaHoaDon.setEditable(false);
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Lưu hóa đơn thất bại");
            e.printStackTrace();
        }
    }

    public void showHoaDonCho() {
        model3.setRowCount(0);
        List<HoaDon> list = hdService.selectByHDChoThanhToan();
        for (HoaDon x : list) {
            model3.addRow(new Object[]{
                x.getMaHD(), XDate.toString(x.getNgayLap()), x.getMaNV()
            });
        }
    }

    public void fillCBOHinhThucThanhToan() {
        DefaultComboBoxModel<HinhThucThanhToan> model = (DefaultComboBoxModel) cboHinhThucTT.getModel();
        model.removeAllElements();
        List<HinhThucThanhToan> list = htttService.selectAll();
        for (HinhThucThanhToan x : list) {
            model.addElement(x);
        }
    }

    public void fillCBOHinhThucGiaoHang() {
        DefaultComboBoxModel<HinhThucGiaoHang> model = (DefaultComboBoxModel) cboHinhThucGiaoHang.getModel();
        model.removeAllElements();
        List<HinhThucGiaoHang> list = htghService.selectAll();
        for (HinhThucGiaoHang x : list) {
            model.addElement(x);
        }
    }

    public void fillTable() {
        model1.setRowCount(0);
        List<SanPhamChiTiet> list = spService.selectAll_BY_ONL();
        for (SanPhamChiTiet x : list) {
            model1.addRow(new Object[]{
                x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getGiaBan(), x.getTenMauSac(), x.getTenChatLieu(), x.getChieuDai() + "cm X " + x.getChieuRong() + "cm X " + x.getChieuCao() + "cm",
                x.getTheTich(), x.getSoLuong()
            });
        }
    }

    public void clickHoaDonCho() {
        row3 = tblHoaDonCho.getSelectedRow();
        txtMaHoaDon.setText(tblHoaDonCho.getValueAt(row3, 0) + "");
        try {
            HoaDon hd = hdService.selectById(txtMaHoaDon.getText());
            lblMaKH.setText(hd.getMaKH());
            lblTenKH.setText(hd.getTenKH());
            lblTongTien.setText(hd.getTongTien() + "");
            lblKhacCanTra.setText(hd.getTongTien() + "");
            txtTienTraKhach.setText(hd.getTienThuaTraKhach() + "");
            cboHinhThucTT.setSelectedItem(hd.getTenHTTT());
            cboHinhThucGiaoHang.setSelectedItem(hd.getTenHTGH());

            model2.setRowCount(0);
            List<HoaDonChiTiet> list = hdctService.selectById(txtMaHoaDon.getText());
            for (HoaDonChiTiet x : list) {
                model2.addRow(new Object[]{
                    x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getDonGia(), x.getSoLuong()
                });
            }
            txtMaHoaDon.setEditable(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void showTTKH() {
        if (KhachHangJframe.maKH == null && KhachHangJframe.tenKH == null) {
            Msgbox.alert(this, "Vui lòng chọn khách hàng trước khi show!");
        } else {
            lblMaKH.setText(KhachHangJframe.maKH);
            lblTenKH.setText(KhachHangJframe.tenKH);
            KhachHangJframe.maKH = null;
            KhachHangJframe.tenKH = null;
        }
    }

    public boolean checkTrungMaHD(String x) {
        boolean check = false;
        List<HoaDon> list = hdService.selectAll();
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getMaHD().equals(x)) {
                check = true;
                break;
            }
        }
        return check;
    }

    public void xuatHoaDon() {
        HoaDon hd = hdService.selectById(txtMaHoaDon.getText());
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(new File("./src/com/dienmaydo/pdf/" + txtMaHoaDon.getText() + ".pdf")));

            document.open();

            Paragraph maHD2 = new Paragraph(txtMaHoaDon.getText());
            Paragraph tenKH2 = new Paragraph(hd.getTenKH());
            Paragraph diaChi2 = new Paragraph(hd.getDiaChi());
            Paragraph soDienThoai2 = new Paragraph(hd.getSdt());

            Paragraph tieuDe = new Paragraph("HOA DON THANH TOAN", FontFactory.getFont(FontFactory.TIMES_ROMAN, 20, Font.BOLDITALIC));
            Paragraph ngayThang = new Paragraph("Thoi gian: " + XDate.toString(hd.getNgayLap()), FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.BOLDITALIC));
            Paragraph maHD1 = new Paragraph("Ma hoa don: " + maHD2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));
            Paragraph tenKH1 = new Paragraph("Khach hang: " + tenKH2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));
            Paragraph diaChi1 = new Paragraph("Dia chi: " + diaChi2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));
            Paragraph soDienThoai1 = new Paragraph("SDT: " + soDienThoai2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));

            tieuDe.setAlignment(Element.ALIGN_CENTER);
            ngayThang.setAlignment(Element.ALIGN_CENTER);
            ngayThang.setSpacingAfter(15);
            maHD1.setAlignment(Element.ALIGN_RIGHT);
            tenKH1.setSpacingBefore(15);
            tenKH1.setAlignment(Element.ALIGN_LEFT);
            diaChi1.setAlignment(Element.ALIGN_LEFT);
            soDienThoai1.setAlignment(Element.ALIGN_LEFT);
            soDienThoai1.setSpacingAfter(15);

            PdfPTable table = new PdfPTable(5);
            float[] withsKM = {10f, 20f, 10f, 5f, 15f};
            table.setWidthPercentage(100);
            table.setWidths(withsKM);
            table.setSpacingAfter(25);
            PdfPCell tenCot1 = new PdfPCell(new Paragraph("Ma san pham", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
            PdfPCell tenCot2 = new PdfPCell(new Paragraph("Ten san pham", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
            PdfPCell tenCot3 = new PdfPCell(new Paragraph("Don Gia", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
            PdfPCell tenCot4 = new PdfPCell(new Paragraph("So luong", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
            PdfPCell tenCot5 = new PdfPCell(new Paragraph("Thanh Tien", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));

            tenCot1.setPadding(5);
            tenCot2.setPadding(5);
            tenCot3.setPadding(5);
            tenCot4.setPadding(5);
            tenCot5.setPadding(5);

            tenCot1.setBackgroundColor(BaseColor.DARK_GRAY);
            tenCot2.setBackgroundColor(BaseColor.DARK_GRAY);
            tenCot3.setBackgroundColor(BaseColor.DARK_GRAY);
            tenCot4.setBackgroundColor(BaseColor.DARK_GRAY);
            tenCot5.setBackgroundColor(BaseColor.DARK_GRAY);

            tenCot1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tenCot2.setHorizontalAlignment(Element.ALIGN_CENTER);
            tenCot3.setHorizontalAlignment(Element.ALIGN_CENTER);
            tenCot4.setHorizontalAlignment(Element.ALIGN_CENTER);
            tenCot5.setHorizontalAlignment(Element.ALIGN_CENTER);

            table.addCell(tenCot1);
            table.addCell(tenCot2);
            table.addCell(tenCot3);
            table.addCell(tenCot4);
            table.addCell(tenCot5);

            for (int i = 0; i < tblSanPhamChon.getRowCount(); i++) {
                PdfPCell data1 = new PdfPCell(new Paragraph(tblSanPhamChon.getValueAt(i, 0) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                PdfPCell data2 = new PdfPCell(new Paragraph(tblSanPhamChon.getValueAt(i, 1) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                PdfPCell data3 = new PdfPCell(new Paragraph(tblSanPhamChon.getValueAt(i, 2) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                PdfPCell data4 = new PdfPCell(new Paragraph(tblSanPhamChon.getValueAt(i, 3) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                PdfPCell data5 = new PdfPCell(new Paragraph(Float.parseFloat(tblSanPhamChon.getValueAt(i, 2) + "") * Integer.parseInt(tblSanPhamChon.getValueAt(i, 3) + "") + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));

                data1.setHorizontalAlignment(Element.ALIGN_CENTER);
                data2.setHorizontalAlignment(Element.ALIGN_CENTER);
                data3.setHorizontalAlignment(Element.ALIGN_CENTER);
                data4.setHorizontalAlignment(Element.ALIGN_CENTER);
                data5.setHorizontalAlignment(Element.ALIGN_CENTER);

                table.addCell(data1);
                table.addCell(data2);
                table.addCell(data3);
                table.addCell(data4);
                table.addCell(data5);
            }

            int tongSL = 0;
            for (int i = 0; i < tblSanPhamChon.getRowCount(); i++) {
                tongSL += Integer.parseInt(tblSanPhamChon.getValueAt(i, 3) + "");
            }

            PdfPCell data1 = new PdfPCell(new Paragraph("TONG:", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
            PdfPCell data2 = new PdfPCell(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
            PdfPCell data3 = new PdfPCell(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
            PdfPCell data4 = new PdfPCell(new Paragraph(tongSL + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
            PdfPCell data5 = new PdfPCell(new Paragraph(lblTongTien.getText(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));

            data1.setHorizontalAlignment(Element.ALIGN_CENTER);
            data2.setHorizontalAlignment(Element.ALIGN_CENTER);
            data3.setHorizontalAlignment(Element.ALIGN_CENTER);
            data4.setHorizontalAlignment(Element.ALIGN_CENTER);
            data5.setHorizontalAlignment(Element.ALIGN_CENTER);

            data1.setPadding(5);
            data2.setPadding(5);
            data3.setPadding(5);
            data4.setPadding(5);
            data5.setPadding(5);

            table.addCell(data1);
            table.addCell(data2);
            table.addCell(data3);
            table.addCell(data4);
            table.addCell(data5);

            Paragraph footer = new Paragraph("NGUOI LAP HOA DON", FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.BOLDITALIC));
            Paragraph nguoiLap = new Paragraph(hd.getTenNV(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 14));
            footer.setAlignment(Element.ALIGN_RIGHT);
            nguoiLap.setAlignment(Element.ALIGN_RIGHT);
            nguoiLap.setIndentationRight(20);

            document.add(tieuDe);
            document.add(ngayThang);
            document.add(maHD1);
            document.add(tenKH1);
            document.add(diaChi1);
            document.add(soDienThoai1);
            document.add(table);
            document.add(footer);
            document.add(nguoiLap);

            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        jPanel8.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));
        executor.execute(this);
    }

    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }

            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException e) {

            }

            if (result != null) {
                model1.setRowCount(0);
                SanPhamChiTiet x = spService.selectWebcam(result.getText());
                model1.addRow(new Object[]{
                    x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getGiaBan(), x.getTenMauSac(), x.getTenChatLieu(), x.getChieuDai() + "cm X " + x.getChieuRong() + "cm X " + x.getChieuCao() + "cm",
                    x.getTheTich(), x.getSoLuong()
                });
                cboDanhMuc.setSelectedIndex(0);

            }
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }

}
