/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dienmaydo.gui;

import com.dienmaydo.entity.HoaDon;
import com.dienmaydo.entity.HoaDonChiTiet;
import com.dienmaydo.service.HoaDonChiTietService;
import com.dienmaydo.service.HoaDonService;
import com.dienmaydo.utils.Msgbox;
import com.dienmaydo.utils.XDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DO TAT HOA
 */
public class F_HoaDon extends javax.swing.JInternalFrame {

    HoaDonChiTietService hdctService = new HoaDonChiTietService();
    HoaDonService hdService = new HoaDonService();
    int row = -1;

    /**
     * Creates new form F_HoaDon
     */
    public F_HoaDon() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChiTietHoaDoon = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDon3 = new javax.swing.JTable();
        txtTimKiem3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1146, 768));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblChiTietHoaDoon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn chi tiết", "Mã sản phẩm", "Tên sản phẩm chi tiết", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblChiTietHoaDoon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblHoaDon3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tổng tiền", "Hình thức thanh toán", "Ngày lập hóa đơn", "Trạng thái thanh toán", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDon3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDon3);

        txtTimKiem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem3KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Tìm kiếm hóa đơn:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnXuatHoaDon.setBackground(new java.awt.Color(255, 204, 0));
        btnXuatHoaDon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXuatHoaDon.setForeground(new java.awt.Color(51, 51, 51));
        btnXuatHoaDon.setText("Xuất hóa đơn");
        btnXuatHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(btnXuatHoaDon)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void tblHoaDon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon3MouseClicked
        // TODO add your handling code here:
        clickHoaDon();
    }//GEN-LAST:event_tblHoaDon3MouseClicked

    private void txtTimKiem3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem3KeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_txtTimKiem3KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblChiTietHoaDoon;
    private javax.swing.JTable tblHoaDon3;
    private javax.swing.JTextField txtTimKiem3;
    // End of variables declaration//GEN-END:variables

    public void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon3.getModel();
        model.setRowCount(0);
        String key = txtTimKiem3.getText();
        List<HoaDon> list = hdService.selectById(key);
        for (HoaDon x : list) {
            model.addRow(new Object[]{
                x.getMaHD(), x.getTongTien() + " VNĐ", x.getHinhThuc_TT(), XDate.toString(x.getNgayLap()), x.getTrangThai_TT()
            });
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon3.getModel();
        model.setRowCount(0);
        List<HoaDon> list = hdService.selectAll();
        for (HoaDon x : list) {
            model.addRow(new Object[]{
                x.getMaHD(), x.getTongTien(), x.getHinhThuc_TT(), XDate.toString(x.getNgayLap()), x.getTrangThai_TT(),x.getGhiChu()
            });
        }
    }

    public void delete() {
        row = tblHoaDon3.getSelectedRow();
        String maHD = (String) tblHoaDon3.getValueAt(row, 0);
        if (row < 0) {
            Msgbox.alert(this, "Vui lòng chọn hóa đơn!");
            return;
        } else {
            if (Msgbox.confirm(this, "Bạn chắc chắn muốn xóa hóa đơn này?")) {
                try {
                    hdService.delete(maHD);
                    fillTable();
                    Msgbox.alert(this, "Xóa hóa đơn thành công");
                } catch (Exception e) {
                    e.printStackTrace();
                    Msgbox.alert(this, "Xóa hóa đơn thất bại");
                }
            }
        }
    }

    public void clickHoaDon() {
        row = tblHoaDon3.getSelectedRow();
        String maHD = tblHoaDon3.getValueAt(row, 0) + "";
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDoon.getModel();
        model.setRowCount(0);
        List<HoaDonChiTiet> list = hdctService.selectById(maHD);
        for (HoaDonChiTiet x : list) {
            model.addRow(new Object[]{
                x.getMaHDCT(), x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getSoLuong(), x.getDonGia(), x.getDonGia() * x.getSoLuong()
            });
        }
    }

    public void update() {
        if (row < 0) {
            Msgbox.alert(this, "Vui lòng chọn hóa đơn!");
            return;
        } else {
            HoaDon hd = new HoaDon();
            hd.setMaHD(tblHoaDon3.getValueAt(row, 0) + "");
            hd.setTongTien(Float.parseFloat(tblHoaDon3.getValueAt(row, 1) + ""));
            hd.setHinhThuc_TT(tblHoaDon3.getValueAt(row, 2) + "");
            hd.setTrangThai_TT(tblHoaDon3.getValueAt(row, 4) + "");
            hd.setGhiChu(tblHoaDon3.getValueAt(row, 5)+"");

            List<HoaDonChiTiet> list = new ArrayList<>();
            for (int i = 0; i < tblChiTietHoaDoon.getRowCount(); i++) {
                HoaDonChiTiet hdct = new HoaDonChiTiet();
                hdct.setMaHDCT(Integer.parseInt(tblChiTietHoaDoon.getValueAt(i, 0) + ""));
                hdct.setMaSPCT(tblChiTietHoaDoon.getValueAt(i, 1) + "");
                hdct.setTenSPCT(tblChiTietHoaDoon.getValueAt(i, 2) + "");
                hdct.setSoLuong(Integer.parseInt(tblChiTietHoaDoon.getValueAt(i, 3) + ""));
                hdct.setDonGia(Float.parseFloat(tblChiTietHoaDoon.getValueAt(i, 4) + ""));

                list.add(hdct);
            }
            Dashboard d = new Dashboard();
            d.goiChucNangBanHang(hd, list);
        }
    }
}
