/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dienmaydo.gui;

import com.dienmaydo.entity.HoaDon;
import com.dienmaydo.entity.HoaDonChiTiet;
import com.dienmaydo.service.HoaDonChiTietService;
import com.dienmaydo.service.HoaDonService;
import com.dienmaydo.utils.Msgbox;
import com.dienmaydo.utils.XDate;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DO TAT HOA
 */
public class F_HoaDon extends javax.swing.JInternalFrame {

    HoaDonChiTietService hdctService = new HoaDonChiTietService();
    HoaDonService hdService = new HoaDonService();
    int row = -1;

    /**
     * Creates new form F_HoaDon
     */
    public F_HoaDon() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChiTietHoaDoon = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDon3 = new javax.swing.JTable();
        txtTimKiem3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1146, 768));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblChiTietHoaDoon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn chi tiết", "Mã sản phẩm", "Tên sản phẩm chi tiết", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblChiTietHoaDoon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblHoaDon3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tổng tiền", "Tiền thừa trả khách", "Hình thức thanh toán", "Hình thức giao hàng", "Ngày lập hóa đơn", "Trạng thái thanh toán", "Mã NV", "Mã KH", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDon3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDon3);

        txtTimKiem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem3KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Tìm kiếm hóa đơn:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnXuatHoaDon.setBackground(new java.awt.Color(255, 204, 0));
        btnXuatHoaDon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXuatHoaDon.setForeground(new java.awt.Color(51, 51, 51));
        btnXuatHoaDon.setText("Xuất hóa đơn");
        btnXuatHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
        xuatHoaDon();
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void tblHoaDon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon3MouseClicked
        // TODO add your handling code here:
        clickHoaDon();
    }//GEN-LAST:event_tblHoaDon3MouseClicked

    private void txtTimKiem3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem3KeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_txtTimKiem3KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblChiTietHoaDoon;
    private javax.swing.JTable tblHoaDon3;
    private javax.swing.JTextField txtTimKiem3;
    // End of variables declaration//GEN-END:variables

    public void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon3.getModel();
        model.setRowCount(0);
        String key = txtTimKiem3.getText();
        List<HoaDon> list = hdService.selectByTimKiem(key);
        for (HoaDon x : list) {
            model.addRow(new Object[]{
                x.getMaHD(), x.getTongTien() + " VND", x.getHinhThuc_TT(), XDate.toString(x.getNgayLap()), x.getTrangThai_TT()
            });
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon3.getModel();
        model.setRowCount(0);
        List<HoaDon> list = hdService.selectAll();
        for (HoaDon x : list) {
            model.addRow(new Object[]{
                x.getMaHD(), x.getTongTien() + " VND", x.getTienThuaTraKhach() + " VND", x.getHinhThuc_TT(), x.getHinhThucGiaoHang(),
                XDate.toString(x.getNgayLap()), x.getTrangThai_TT(), x.getMaNV(), x.getMaKH(), x.getGhiChu()
            });
        }
    }

    public void clickHoaDon() {
        row = tblHoaDon3.getSelectedRow();
        String maHD = tblHoaDon3.getValueAt(row, 0) + "";
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDoon.getModel();
        model.setRowCount(0);
        List<HoaDonChiTiet> list = hdctService.selectById(maHD);
        for (HoaDonChiTiet x : list) {
            model.addRow(new Object[]{
                x.getMaHDCT(), x.getMaSPCT(), x.getTenSP() + " " + x.getTenSPCT(), x.getSoLuong(), x.getDonGia() + " VND", x.getDonGia() * x.getSoLuong() + " VND"
            });
        }
    }

    public void xuatHoaDon() {
        if (row < 0) {
            Msgbox.alert(this, "Vui lòng chọn hóa đơn để xuất");
        } else {
            if (Msgbox.confirm(this, "Bạn muốn xuất hóa đơn này?")) {
                HoaDon hd = hdService.selectById(tblHoaDon3.getValueAt(row, 0) + "");
                Document document = new Document();
                try {
                    PdfWriter.getInstance(document, new FileOutputStream(new File("./src/com/dienmaydo/pdf/"+tblHoaDon3.getValueAt(row, 0)+".pdf")));

                    document.open();

                    Paragraph maHD2 = new Paragraph(tblHoaDon3.getValueAt(row, 0) + "");
                    Paragraph tenKH2 = new Paragraph(hd.getTenKH());
                    Paragraph diaChi2 = new Paragraph(hd.getDiaChi());
                    Paragraph soDienThoai2 = new Paragraph(hd.getSdt());

                    Paragraph tieuDe = new Paragraph("HOA DON THANH TOAN", FontFactory.getFont(FontFactory.TIMES_ROMAN, 20, Font.BOLDITALIC));
                    Paragraph ngayThang = new Paragraph("Thoi gian: " + XDate.toString(hd.getNgayLap()), FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.BOLDITALIC));
                    Paragraph maHD1 = new Paragraph("Ma hoa don: " + maHD2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));
                    Paragraph tenKH1 = new Paragraph("Khach hang: " + tenKH2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));
                    Paragraph diaChi1 = new Paragraph("Dia chi: " + diaChi2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));
                    Paragraph soDienThoai1 = new Paragraph("SDT: " + soDienThoai2, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC));

                    tieuDe.setAlignment(Element.ALIGN_CENTER);
                    ngayThang.setAlignment(Element.ALIGN_CENTER);
                    ngayThang.setSpacingAfter(15);
                    maHD1.setAlignment(Element.ALIGN_RIGHT);
                    tenKH1.setSpacingBefore(15);
                    tenKH1.setAlignment(Element.ALIGN_LEFT);
                    diaChi1.setAlignment(Element.ALIGN_LEFT);
                    soDienThoai1.setAlignment(Element.ALIGN_LEFT);
                    soDienThoai1.setSpacingAfter(15);

                    PdfPTable table = new PdfPTable(5);
                    float[] withsKM = {10f, 20f, 10f, 5f, 15f};
                    table.setWidthPercentage(100);
                    table.setWidths(withsKM);
                    table.setSpacingAfter(25);
                    PdfPCell tenCot1 = new PdfPCell(new Paragraph("Ma san pham", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
                    PdfPCell tenCot2 = new PdfPCell(new Paragraph("Ten san pham", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
                    PdfPCell tenCot3 = new PdfPCell(new Paragraph("Don Gia", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
                    PdfPCell tenCot4 = new PdfPCell(new Paragraph("So luong", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));
                    PdfPCell tenCot5 = new PdfPCell(new Paragraph("Thanh Tien", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLDITALIC, new CMYKColor(0, 0, 0, 0))));

                    tenCot1.setPadding(5);
                    tenCot2.setPadding(5);
                    tenCot3.setPadding(5);
                    tenCot4.setPadding(5);
                    tenCot5.setPadding(5);

                    tenCot1.setBackgroundColor(BaseColor.DARK_GRAY);
                    tenCot2.setBackgroundColor(BaseColor.DARK_GRAY);
                    tenCot3.setBackgroundColor(BaseColor.DARK_GRAY);
                    tenCot4.setBackgroundColor(BaseColor.DARK_GRAY);
                    tenCot5.setBackgroundColor(BaseColor.DARK_GRAY);

                    tenCot1.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tenCot2.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tenCot3.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tenCot4.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tenCot5.setHorizontalAlignment(Element.ALIGN_CENTER);

                    table.addCell(tenCot1);
                    table.addCell(tenCot2);
                    table.addCell(tenCot3);
                    table.addCell(tenCot4);
                    table.addCell(tenCot5);

                    for (int i = 0; i < tblChiTietHoaDoon.getRowCount(); i++) {
                        PdfPCell data1 = new PdfPCell(new Paragraph(tblChiTietHoaDoon.getValueAt(i, 1) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                        PdfPCell data2 = new PdfPCell(new Paragraph(tblChiTietHoaDoon.getValueAt(i, 2) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                        PdfPCell data3 = new PdfPCell(new Paragraph(tblChiTietHoaDoon.getValueAt(i, 4) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                        PdfPCell data4 = new PdfPCell(new Paragraph(tblChiTietHoaDoon.getValueAt(i, 3) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                        PdfPCell data5 = new PdfPCell(new Paragraph(tblChiTietHoaDoon.getValueAt(i, 5) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));

                        data1.setHorizontalAlignment(Element.ALIGN_CENTER);
                        data2.setHorizontalAlignment(Element.ALIGN_CENTER);
                        data3.setHorizontalAlignment(Element.ALIGN_CENTER);
                        data4.setHorizontalAlignment(Element.ALIGN_CENTER);
                        data5.setHorizontalAlignment(Element.ALIGN_CENTER);

                        table.addCell(data1);
                        table.addCell(data2);
                        table.addCell(data3);
                        table.addCell(data4);
                        table.addCell(data5);
                    }

                    int tongSL = 0;
                    for (int i = 0; i < tblChiTietHoaDoon.getRowCount(); i++) {
                        tongSL += Integer.parseInt(tblChiTietHoaDoon.getValueAt(i, 3)+"");
                    }
                    
                    PdfPCell data1 = new PdfPCell(new Paragraph("Tong:", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                    PdfPCell data2 = new PdfPCell(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                    PdfPCell data3 = new PdfPCell(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                    PdfPCell data4 = new PdfPCell(new Paragraph(tongSL+"", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
                    PdfPCell data5 = new PdfPCell(new Paragraph(tblHoaDon3.getValueAt(row, 1) + "", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));

                    data1.setHorizontalAlignment(Element.ALIGN_CENTER);
                    data2.setHorizontalAlignment(Element.ALIGN_CENTER);
                    data3.setHorizontalAlignment(Element.ALIGN_CENTER);
                    data4.setHorizontalAlignment(Element.ALIGN_CENTER);
                    data5.setHorizontalAlignment(Element.ALIGN_CENTER);

                    data1.setPadding(5);
                    data2.setPadding(5);
                    data3.setPadding(5);
                    data4.setPadding(5);
                    data5.setPadding(5);

                    table.addCell(data1);
                    table.addCell(data2);
                    table.addCell(data3);
                    table.addCell(data4);
                    table.addCell(data5);

                    Paragraph footer = new Paragraph("NGUOI LAP HOA DON", FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, Font.BOLDITALIC));
                    Paragraph nguoiLap = new Paragraph(hd.getTenNV(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 14));
                    footer.setAlignment(Element.ALIGN_RIGHT);
                    nguoiLap.setAlignment(Element.ALIGN_RIGHT);
                    nguoiLap.setIndentationRight(20);

                    document.add(tieuDe);
                    document.add(ngayThang);
                    document.add(maHD1);
                    document.add(tenKH1);
                    document.add(diaChi1);
                    document.add(soDienThoai1);
                    document.add(table);
                    document.add(footer);
                    document.add(nguoiLap);

                    document.close();
                    Msgbox.alert(this, "Xuất hóa đơn thành công");
                } catch (Exception e) {
                    Msgbox.alert(this, "Xuất hóa đơn thất bại");
                    e.printStackTrace();
                }
            }
        }
    }

}
